before_install:
  - sudo apt install -yqq tree &&
script:
  - cp tests/options.docker_compose_example.yml tests/options.yml
  - "echo 'TODO: run user creation script'"
  - tree -L 3
  - cat ./tests/options.yml
  - #docker-compose run python_libstorj python -m unittest discover
