language: python
python:
  - '2.6'
  - '2.7'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig git build-essential libtool autotools-dev automake libmicrohttpd-dev bsdmainutils libcurl4-gnutls-dev nettle-dev libjson-c-dev libuv1-dev
  - install_libstorj.sh
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover